### ISSUE TITLE
Cards per row is seen to be 2 on sol as compared to 4 on mvx.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/bitzxp-dapp#15]
Cards per row is seen to be 2 on sol as compared to 4 on mvx.

![image](https://github.com/Itheum/cNFT-gallery/assets/121969933/61e43549-1c69-4526-b6ed-b93cec45e6dc)

![image](https://github.com/Itheum/cNFT-gallery/assets/121969933/de7b9c64-88bc-421b-8198-c18f1597cef7)

**Comment by damienen** [comment]
Solved to be dynamic depending on space on screen. Closing
