### ISSUE TITLE
Header elements to be similar to datadex

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/bitzxp-dapp#23]
Header to be similar to datadex to have them look similar from a Brand alignment perspective. 

1. Wallet wallet to be placed on the right and stylised similar to datadex.

![image](https://github.com/Itheum/cNFT-gallery/assets/121969933/9b68bfb6-ca2f-47ef-95aa-7d3352033a9c)

2. Darkmode/lightmode

3. Points display

![image](https://github.com/Itheum/cNFT-gallery/assets/121969933/29edb505-bdd2-45b8-bced-48f2761d65b9)

**Comment by damienen** [comment]
Also delete settings cogwheel

**Comment by damienen** [comment]
Copy bridge logo and writing style

**Comment by damienen** [comment]
Wallet wallet to be placed on the right and stylised similar to bridge => SOLVED
delete settings cogwheel => SOLVED
Copy bridge logo and writing style => SOLVED
Points display => SOLVED

Darkmode/lightmode => DEFFERED
