### ISSUE TITLE
[B] When giving BiTz there is an issue in saving/updating points

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/bitzxp-dapp#5]
When giving BiTz there is an issue in saving/updating points. The amount given is fine, but the number of givers does not update, neither does the leaderboard. 

On refreshing all given BiTz seem to be reset on the bounty card.

![image](https://github.com/Itheum/cNFT-gallery/assets/121969933/4ab48c02-6d4b-4ab9-a471-def25737d7ee)

**Comment by damienen** [comment]
Solved. Closing
